---
语文: zm
数学: cjun
英语: xmh
物理: zxs
化学: zjx
地理杨: ysh
地理周: zjp
陈忠伟: czw
钟志兴: zzx
EL: $python -m pygame.examples.eventlist
DIR: D:\英语早读\选修8 课本录音
FILE: D:\英语早读\选修8 课本录音\Reading.mp3
...
---
zzx: "1234"
...
---
style: MaterialBlue
